import type { Metadata } from 'next'
import { Toaster } from 'sonner'
import '../styles/globals.css'

import { ThemeProvider } from '@/components/theme-provider'

import { geistMono, geistSans } from '../styles/fonts'

export const metadata: Metadata = {
	title: 'Healthcare System',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					disableTransitionOnChange
					enableSystem
				>
					{children}
					<Toaster
						position="top-center"
						richColors
					/>
				</ThemeProvider>
			</body>
		</html>
	)
}
